import { Product, BlogPost, Faq } from './types';

const baseBows = [
  {
    "title": "Apex Rush Kid's Gift Pack - 30lbs Compound Bow",
    "priceAud": 209.95,
    "priceGbp": 109,
    "priceUsd": 136,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex rush kid's gift pack - 30lbs compound bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBK2-xx-GP.jpg?20241127155447"
  },
  {
    "title": "Apex Rush 30lbs Youth Compound Bow",
    "priceAud": 149.95,
    "priceGbp": 78,
    "priceUsd": 97,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex rush 30lbs youth compound bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBK2-xx.jpg?20240906155158"
  },
  {
    "title": "Podium Recurve Bow package - Zone Archery",
    "priceAud": 199.95,
    "priceGbp": 104,
    "priceUsd": 130,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "podium recurve bow package - zone archery",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TP-R2-PACKAGE.jpg?20220119151910"
  },
  {
    "title": "Apex Rush Kid's Gift Pack - 30lbs Compound Bow - T",
    "priceAud": 209.95,
    "priceGbp": 109,
    "priceUsd": 136,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex rush kid's gift pack - 30lbs compound bow - t",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBK2-TTS-GP.jpg?20241127155651"
  },
  {
    "title": "Bear Royale RTH Youth Compound Bow",
    "priceAud": 549.95,
    "priceGbp": 286,
    "priceUsd": 357,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear royale rth youth compound bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/117151-1000.jpg?20250416144249"
  },
  {
    "title": "Kids Archery Gift Set - 15lbs Red LongBow",
    "priceAud": 79.95,
    "priceGbp": 42,
    "priceUsd": 52,
    "cat": "Longbows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "kids archery gift set - 15lbs red longbow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-RB010-GP.jpg?20210309034457"
  },
  {
    "title": "Samick Sage Takedown Recurve",
    "priceAud": 249.95,
    "priceGbp": 130,
    "priceUsd": 162,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "samick sage takedown recurve",
    "image": "https://www.apexhunting.com.au/assets/thumbL/SS-SAGE.png?20220309094956"
  },
  {
    "title": "Traditional Recurve Bow package - Zone Archery",
    "priceAud": 199.95,
    "priceGbp": 104,
    "priceUsd": 130,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "traditional recurve bow package - zone archery",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TP-R7-PACKAGE.jpg?20220119151821"
  },
  {
    "title": "Apex Mayhem Compound Bow - RTS Series",
    "priceAud": 359.95,
    "priceGbp": 187,
    "priceUsd": 234,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex mayhem compound bow - rts series",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CB60-XX-RTS.jpg?20241003091036"
  },
  {
    "title": "Apex Rush Kid's Gift Pack - 30lbs Compound Bow - B",
    "priceAud": 209.95,
    "priceGbp": 109,
    "priceUsd": 136,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex rush kid's gift pack - 30lbs compound bow - b",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBK2-BK-GP.jpg?20241127155700"
  },
  {
    "title": "Apex Rush Kid's Gift Pack - 30lbs Compound Bow - G",
    "priceAud": 209.95,
    "priceGbp": 109,
    "priceUsd": 136,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex rush kid's gift pack - 30lbs compound bow - g",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBK2-GN-GP.jpg?20241127155726"
  },
  {
    "title": "Apex Sambar Compound Bow RTS Series",
    "priceAud": 549.95,
    "priceGbp": 286,
    "priceUsd": 357,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex sambar compound bow rts series",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBA7-xx-RTS.jpg?20240911165510"
  },
  {
    "title": "Bear Archery Paradigm RTH Compound Bow",
    "priceAud": 1049.95,
    "priceGbp": 546,
    "priceUsd": 682,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear archery paradigm rth compound bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/120370-1000.jpg?20250404095211"
  },
  {
    "title": "Bear Cruzer G4 Field Ready Kit",
    "priceAud": 1169.95,
    "priceGbp": 608,
    "priceUsd": 760,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear cruzer g4 field ready kit",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-CRUZERG4FRK.jpg?20250804141233"
  },
  {
    "title": "Bear Cruzer G4 RTH RH Mossy Oak Roots Field Ready",
    "priceAud": 1169.95,
    "priceGbp": 608,
    "priceUsd": 760,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear cruzer g4 rth rh mossy oak roots field ready",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-AV54A210R7R-FRK.jpg?20250804141321"
  },
  {
    "title": "Field Ready Upgrade Kit for Compound Bows",
    "priceAud": 194.95,
    "priceGbp": 101,
    "priceUsd": 127,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "field ready upgrade kit for compound bows",
    "image": "https://www.apexhunting.com.au/assets/thumbL/AH-FR-KIT.jpg?20210309034535"
  },
  {
    "title": "Field Ready Upgrade Kit for Compound Bows Large",
    "priceAud": 339.95,
    "priceGbp": 177,
    "priceUsd": 221,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "field ready upgrade kit for compound bows large",
    "image": "https://www.apexhunting.com.au/assets/thumbL/AH-FR-KIT.jpg?20210309034535"
  },
  {
    "title": "Grizzly Traditional Recurve Bow  - Bear Archery",
    "priceAud": 689.95,
    "priceGbp": 359,
    "priceUsd": 448,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "grizzly traditional recurve bow  - bear archery",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-AFT20861--.jpg?20250331145639"
  },
  {
    "title": "Hunter Recurve Bow package - Zone Archery",
    "priceAud": 239.95,
    "priceGbp": 125,
    "priceUsd": 156,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "hunter recurve bow package - zone archery",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TP-R3-PACKAGE.jpg?20220119152553"
  },
  {
    "title": "Old Mountain Archery Stingray 60 Inch Recurve Bow",
    "priceAud": 379.95,
    "priceGbp": 198,
    "priceUsd": 247,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "old mountain archery stingray 60 inch recurve bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/OMA-STINGRAY.jpg?20251119142434"
  },
  {
    "title": "Old Mountain Archery Tracker 52 Inch Horsebow",
    "priceAud": 349.95,
    "priceGbp": 182,
    "priceUsd": 227,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "old mountain archery tracker 52 inch horsebow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/OMA-TRACKER.jpg?20251119142819"
  },
  {
    "title": "Samick Sage Limbs",
    "priceAud": 139.95,
    "priceGbp": 73,
    "priceUsd": 91,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "samick sage limbs",
    "image": "https://www.apexhunting.com.au/assets/thumbL/SS-SAGE-LIMBS.png?20220221163810"
  },
  {
    "title": "Apex Berserker Evolve 75 - RTS",
    "priceAud": 399.95,
    "priceGbp": 208,
    "priceUsd": 260,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex berserker evolve 75 - rts",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CB75xx-RTS.jpg?20241104135344"
  },
  {
    "title": "Apex Sambar Compound Bow Field Ready Kit",
    "priceAud": 899.95,
    "priceGbp": 468,
    "priceUsd": 585,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex sambar compound bow field ready kit",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBA7-xx-FR.jpg?20240920104531"
  },
  {
    "title": "Apex Sambar Compound Bow Field Ready Kit - Black -",
    "priceAud": 899.95,
    "priceGbp": 468,
    "priceUsd": 585,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex sambar compound bow field ready kit - black -",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBA7-BK-FR-LH.jpg?20240920104806"
  },
  {
    "title": "Apex Sambar Compound Bow Pro Series",
    "priceAud": 599.95,
    "priceGbp": 312,
    "priceUsd": 390,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "apex sambar compound bow pro series",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-CBA7-xx-PRO.jpg?20240920104850"
  },
  {
    "title": "Bear Adapt 2+ HP Compound Bow Package",
    "priceAud": 1469.95,
    "priceGbp": 764,
    "priceUsd": 955,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear adapt 2+ hp compound bow package",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-ADAPT2PLUSHPRTH.webp?20251021135839"
  },
  {
    "title": "Bear Adapt 2+ HP RTH RH 70lbs Mossy Oak Bottomland",
    "priceAud": 1469.95,
    "priceGbp": 764,
    "priceUsd": 955,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear adapt 2+ hp rth rh 70lbs mossy oak bottomland",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-AV67A720B7R.webp?20251021141224"
  },
  {
    "title": "Bear Alaskan Pro RTH 2026 Compound Bow Package",
    "priceAud": 1229.95,
    "priceGbp": 640,
    "priceUsd": 799,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear alaskan pro rth 2026 compound bow package",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-ALASKANPRORTH.webp?20251016121708"
  },
  {
    "title": "Bear Cheyenne One Piece Traditional Recurve Bow",
    "priceAud": 899.95,
    "priceGbp": 468,
    "priceUsd": 585,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear cheyenne one piece traditional recurve bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/106706-1000.jpg?20250616164717"
  },
  {
    "title": "Bear Legit Maxx Field Ready Kit",
    "priceAud": 1179.95,
    "priceGbp": 614,
    "priceUsd": 767,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear legit maxx field ready kit",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-LEGITMAXXFRK.jpg?20250804141502"
  },
  {
    "title": "Bear Legit Maxx RTH RH Mossy Oak Roots Field Ready",
    "priceAud": 1179.95,
    "priceGbp": 614,
    "priceUsd": 767,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear legit maxx rth rh mossy oak roots field ready",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-AV54A230R7R-FRK.jpg?20250804141513"
  },
  {
    "title": "Bear Resilient RTH Compound Bow Package",
    "priceAud": 1079.95,
    "priceGbp": 562,
    "priceUsd": 702,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear resilient rth compound bow package",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-RESILIENTRTH.webp?20251021121301"
  },
  {
    "title": "Bear Resilient RTH RH 70lbs Emerge 2.0",
    "priceAud": 1079.95,
    "priceGbp": 562,
    "priceUsd": 702,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear resilient rth rh 70lbs emerge 2.0",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-AV66B83027R.webp?20251021131402"
  },
  {
    "title": "Bear Royale RTH Youth Compound Bow Left Handed / M",
    "priceAud": 559.95,
    "priceGbp": 291,
    "priceUsd": 364,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear royale rth youth compound bow left handed / m",
    "image": "https://www.apexhunting.com.au/assets/thumbL/117151-1090.png?20240531113429"
  },
  {
    "title": "Bear Royale RTH Youth Compound Bow Right Handed /",
    "priceAud": 559.95,
    "priceGbp": 291,
    "priceUsd": 364,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear royale rth youth compound bow right handed /",
    "image": "https://www.apexhunting.com.au/assets/thumbL/117151-1006.png?20240531113419"
  },
  {
    "title": "Bear Royale RTH Youth Compound Bow Right Handed /",
    "priceAud": 559.95,
    "priceGbp": 291,
    "priceUsd": 364,
    "cat": "Youth",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear royale rth youth compound bow right handed /",
    "image": "https://www.apexhunting.com.au/assets/thumbL/117151-1048.png?20210309035317"
  },
  {
    "title": "Bear Traditional Little Bear / Right Handed / 20lb",
    "priceAud": 399.95,
    "priceGbp": 208,
    "priceUsd": 260,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "bear traditional little bear / right handed / 20lb",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BA-ALB23.jpg?20250331145454"
  },
  {
    "title": "Black Sheep Rocket Recurve Bow Limbs",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "black sheep rocket recurve bow limbs",
    "image": "https://www.apexhunting.com.au/assets/thumbL/114535-1000.jpg?20210309034841"
  },
  {
    "title": "Hoyt Enduro Premier Package Compound Bow",
    "priceAud": 1599.95,
    "priceGbp": 832,
    "priceUsd": 1040,
    "cat": "Kits",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "hoyt enduro premier package compound bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/122223-1000.jpg?20251119164637"
  },
  {
    "title": "Kids Archery Gift Set - 10lbs Red LongBow",
    "priceAud": 79.95,
    "priceGbp": 42,
    "priceUsd": 52,
    "cat": "Longbows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "kids archery gift set - 10lbs red longbow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-RB009-GP.jpg?20210309034430"
  },
  {
    "title": "Kids Archery Gift Set - 18lbs Black LongBow",
    "priceAud": 124.95,
    "priceGbp": 65,
    "priceUsd": 81,
    "cat": "Longbows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "kids archery gift set - 18lbs black longbow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MK-MK-RB015-BK-GP.png?20220309104321"
  },
  {
    "title": "Mathews ARC 30 Compound Bow",
    "priceAud": 2399.95,
    "priceGbp": 1248,
    "priceUsd": 1560,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "mathews arc 30 compound bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/122211-1000.jpg?20251119170353"
  },
  {
    "title": "Mathews SwitchWeight-X Modules",
    "priceAud": 129.95,
    "priceGbp": 68,
    "priceUsd": 84,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "mathews switchweight-x modules",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MA-SWXMODS.png?20231123101232"
  },
  {
    "title": "Mathews SwitchWeight-X Modules / 65lbs / 85% / F",
    "priceAud": 129.95,
    "priceGbp": 68,
    "priceUsd": 84,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "mathews switchweight-x modules / 65lbs / 85% / f",
    "image": "https://www.apexhunting.com.au/assets/thumbL/MA-SWXMODS.png?20231123101232"
  },
  {
    "title": "Mathews SWX-Z Module Set",
    "priceAud": 124.95,
    "priceGbp": 65,
    "priceUsd": 81,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "mathews swx-z module set",
    "image": "https://www.apexhunting.com.au/assets/thumbL/122216-1000.jpg?20260610145743"
  },
  {
    "title": "Old Mountain Archery Stingray 60 Inch Recurve Bow",
    "priceAud": 379.95,
    "priceGbp": 198,
    "priceUsd": 247,
    "cat": "Recurve bows",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "old mountain archery stingray 60 inch recurve bow",
    "image": "https://www.apexhunting.com.au/assets/thumbL/OMA-STINGRAY.jpg?20251119142434"
  },
  {
    "title": "Old Mountain Archery Tracker 52 Inch Horsebow 30lb",
    "priceAud": 349.95,
    "priceGbp": 182,
    "priceUsd": 227,
    "cat": "Hunting",
    "speed": "300+ FPS",
    "weight": "4.0 lbs",
    "ata": "32\"",
    "seoKw": "old mountain archery tracker 52 inch horsebow 30lb",
    "image": "https://www.apexhunting.com.au/assets/thumbL/OMA-TRACKER.jpg?20251119142819"
  }
];
const baseArrows = [
  {
    "title": "Terra Firma Gladius 3 Blade Broadheads",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma gladius 3 blade broadheads",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-GD-xxx.jpg?20240418120446"
  },
  {
    "title": "Firefly v2 Lighted Nocks",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "firefly v2 lighted nocks",
    "image": "https://www.apexhunting.com.au/assets/thumbL/YSP-FFv2.png?20240412111515"
  },
  {
    "title": "Terra Firma Gladius Broadhead - 125gn - 3 Pack",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma gladius broadhead - 125gn - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-GD-125.jpg?20240418120632"
  },
  {
    "title": "Terra Firma FORTIS Fletched Arrows - Dozen",
    "priceAud": 184.95,
    "priceGbp": 96,
    "priceUsd": 120,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma fortis fletched arrows - dozen",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-T1FB.jpg?20250428170047"
  },
  {
    "title": "Terra Firma Gladius Broadhead - 150gn - 3 Pack",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma gladius broadhead - 150gn - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-GD-150.jpg?20240418120637"
  },
  {
    "title": "Carbon Blackout Original",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "carbon blackout original",
    "image": "https://www.apexhunting.com.au/assets/thumbL/WJ-ACBO-xxx-.jpg?20210309040052"
  },
  {
    "title": "Terra Firma Venator Broadheads",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma venator broadheads",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-VN-xxx.jpg?20240418111505"
  },
  {
    "title": "Kayuga Broadheads Pilot Cut Gen 2",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "kayuga broadheads pilot cut gen 2",
    "image": "https://www.apexhunting.com.au/assets/thumbL/KA-PC2-x.png?20210309040321"
  },
  {
    "title": "Carbon Blackout Heritage",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "carbon blackout heritage",
    "image": "https://www.apexhunting.com.au/assets/thumbL/WJ-ACBOH-xxx.jpg?20210309040052"
  },
  {
    "title": "Saunders Combo Points",
    "priceAud": 14.95,
    "priceGbp": 8,
    "priceUsd": 10,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "saunders combo points",
    "image": "https://www.apexhunting.com.au/assets/thumbL/SA-96xx.jpg?20210309034819"
  },
  {
    "title": "Terra Firma SICARIO 5mm Shafts",
    "priceAud": 164.95,
    "priceGbp": 86,
    "priceUsd": 107,
    "cat": "Arrow Shafts",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma sicario 5mm shafts",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-SIC-S-xxx.jpg?20250415160522"
  },
  {
    "title": "Arrow Cutting Service",
    "priceAud": 15,
    "priceGbp": 8,
    "priceUsd": 10,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "arrow cutting service",
    "image": "https://www.apexhunting.com.au/assets/thumbL/Cutting-xxx.jpg?20241008144729"
  },
  {
    "title": "Terra Firma Gladius Broadhead - 100gn - 3 Pack",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma gladius broadhead - 100gn - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-GD-xxx.jpg?20240418120446"
  },
  {
    "title": "Terra Firma SICARIO 5mm Fletched Arrows",
    "priceAud": 184.95,
    "priceGbp": 96,
    "priceUsd": 120,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma sicario 5mm fletched arrows",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-SIC-F-xxx.jpg?20250428164738"
  },
  {
    "title": "Kayuga Broadheads Pilot Cut Gen 2 / 6 Pack / 125 G",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "kayuga broadheads pilot cut gen 2 / 6 pack / 125 g",
    "image": "https://www.apexhunting.com.au/assets/thumbL/KA-PC2-125.png?20250117140147"
  },
  {
    "title": "Gold Tip EZ-Pull .246 Field Points",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "gold tip ez-pull .246 field points",
    "image": "https://www.apexhunting.com.au/assets/thumbL/VO-EZPULL.jpg?20250329112152"
  },
  {
    "title": "Terra Firma Field Tips",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma field tips",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-MFT-xxx.jpg?20260505155249"
  },
  {
    "title": "Terra Firma VERTEX 5mm Fletched Arrows",
    "priceAud": 184.95,
    "priceGbp": 96,
    "priceUsd": 120,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma vertex 5mm fletched arrows",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-VTX-F-xxx.jpg?20250428165553"
  },
  {
    "title": "Firefly v2 Lighted Nocks - Size S - Green - 3 Pack",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "firefly v2 lighted nocks - size s - green - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/YSP-FFv2.png?20240412111515"
  },
  {
    "title": "Gold Tip Traditional Fletched Carbon Arrows",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "gold tip traditional fletched carbon arrows",
    "image": "https://www.apexhunting.com.au/assets/thumbL/VO-TRADxxxF6.jpg?20241018100909"
  },
  {
    "title": "Kayuga Broadheads ZOT",
    "priceAud": 79.95,
    "priceGbp": 42,
    "priceUsd": 52,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "kayuga broadheads zot",
    "image": "https://www.apexhunting.com.au/assets/thumbL/KA-ZOT.png?20211122110503"
  },
  {
    "title": "Terra Firma DOMINUS 4mm Fletched Arrows",
    "priceAud": 249.95,
    "priceGbp": 130,
    "priceUsd": 162,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma dominus 4mm fletched arrows",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-DMN-F-xxx.jpg?20250428162540"
  },
  {
    "title": "Firefly v2 Lighted Nocks - Size G - Green - 3 Pack",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "firefly v2 lighted nocks - size g - green - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/YSP-FFv2.png?20240412111515"
  },
  {
    "title": "Firefly v2 Lighted Nocks - Size S - Red - 3 Pack",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "firefly v2 lighted nocks - size s - red - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/YSP-FFv2.png?20240412111515"
  },
  {
    "title": "Terra Firma Pull-Thru Sharpener",
    "priceAud": 39.95,
    "priceGbp": 21,
    "priceUsd": 26,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma pull-thru sharpener",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-PTS.jpg?20251007130318"
  },
  {
    "title": "Terra Firma Venator Broadheads - 100gn - 3 Pack",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma venator broadheads - 100gn - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-VN-100.jpg?20240418111556"
  },
  {
    "title": "Zone Archery Aluminium Arrows - 31.5 Inch - 12 Pac",
    "priceAud": 69.95,
    "priceGbp": 36,
    "priceUsd": 45,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "zone archery aluminium arrows - 31.5 inch - 12 pac",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TP-TPJL.png?20220620095037"
  },
  {
    "title": "Firefly v2 Lighted Nocks - Size X - Red - 3 Pack",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "firefly v2 lighted nocks - size x - red - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/YSP-FFv2.png?20240412111515"
  },
  {
    "title": "Sabretooth Broadheads",
    "priceAud": 29.95,
    "priceGbp": 16,
    "priceUsd": 19,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "sabretooth broadheads",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TP-TP225-100-.jpg?20210309034734"
  },
  {
    "title": "Terra Firma DOMINUS Shafts",
    "priceAud": 229.95,
    "priceGbp": 120,
    "priceUsd": 149,
    "cat": "Arrow Shafts",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma dominus shafts",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-DMN-S.jpg?20250321160017"
  },
  {
    "title": "Terra Firma FORTIS Shafts - Dozen",
    "priceAud": 164.95,
    "priceGbp": 86,
    "priceUsd": 107,
    "cat": "Arrow Shafts",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma fortis shafts - dozen",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-T1S.jpg?20250418164053"
  },
  {
    "title": "Terra Firma Nock Collars",
    "priceAud": 18.95,
    "priceGbp": 10,
    "priceUsd": 12,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma nock collars",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-xxx-COL-xxx.jpg?20250516145549"
  },
  {
    "title": "Terra Firma VERTEX 5mm Fletched Arrows - 12 Pack -",
    "priceAud": 184.95,
    "priceGbp": 96,
    "priceUsd": 120,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma vertex 5mm fletched arrows - 12 pack -",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-VTX-F-xxx.jpg?20250428165553"
  },
  {
    "title": "Nix Broadheads Razr - 2 Blade Single Bevel Broadhe",
    "priceAud": 39.95,
    "priceGbp": 21,
    "priceUsd": 26,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "nix broadheads razr - 2 blade single bevel broadhe",
    "image": "https://www.apexhunting.com.au/assets/thumbL/NIX-RAZR2.webp?20250129134246"
  },
  {
    "title": "Nix Broadheads Razr - 2 Blade Single Bevel Broadhe",
    "priceAud": 39.95,
    "priceGbp": 21,
    "priceUsd": 26,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "nix broadheads razr - 2 blade single bevel broadhe",
    "image": "https://www.apexhunting.com.au/assets/thumbL/NIX-RAZR2.webp?20250129134246"
  },
  {
    "title": "Terra Firma Field Tips - 6 Pack - 100gn",
    "priceAud": 24.95,
    "priceGbp": 13,
    "priceUsd": 16,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma field tips - 6 pack - 100gn",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-MFT-xxx.jpg?20260505155249"
  },
  {
    "title": "Terra Firma SICARIO 5mm Shafts - 300 - 12 Pack",
    "priceAud": 164.95,
    "priceGbp": 86,
    "priceUsd": 107,
    "cat": "Arrow Shafts",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma sicario 5mm shafts - 300 - 12 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-SIC-S-xxx.jpg?20250415160522"
  },
  {
    "title": "Terra Firma VERTEX TRADITIONAL 5mm Fletched Arrows",
    "priceAud": 189.95,
    "priceGbp": 99,
    "priceUsd": 123,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma vertex traditional 5mm fletched arrows",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-VTX-TRAD-xxx.jpg?20250428170316"
  },
  {
    "title": "Bohning Alpha Vane 2.8 Inch 100 Pack",
    "priceAud": 46.95,
    "priceGbp": 24,
    "priceUsd": 31,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "bohning alpha vane 2.8 inch 100 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/BN-ALPHA28.jpg?20241014150025"
  },
  {
    "title": "Carbon Blackout Nano",
    "priceAud": 119.95,
    "priceGbp": 62,
    "priceUsd": 78,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "carbon blackout nano",
    "image": "https://www.apexhunting.com.au/assets/thumbL/WJ-ACBON-xxx-xxx.jpg?20210309040052"
  },
  {
    "title": "Kayuga Broadheads Old School Double Bevel",
    "priceAud": 59.95,
    "priceGbp": 31,
    "priceUsd": 39,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "kayuga broadheads old school double bevel",
    "image": "https://www.apexhunting.com.au/assets/thumbL/KA-OS-x.png?20220714160641"
  },
  {
    "title": "SEVR Magneto Ti 1.75 2-Blade Broadhead",
    "priceAud": 39.95,
    "priceGbp": 21,
    "priceUsd": 26,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "sevr magneto ti 1.75 2-blade broadhead",
    "image": "https://www.apexhunting.com.au/assets/thumbL/SV-MAGNETO175-2B.png?20260714163746"
  },
  {
    "title": "Terra Firma 166 Nocks",
    "priceAud": 12.95,
    "priceGbp": 7,
    "priceUsd": 8,
    "cat": "Arrow Components",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma 166 nocks",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-T1N-x.webp?20250515162253"
  },
  {
    "title": "Terra Firma Curved Leather Strop",
    "priceAud": 34.95,
    "priceGbp": 18,
    "priceUsd": 23,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma curved leather strop",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-CLS.jpg?20251007130457"
  },
  {
    "title": "Terra Firma Venator Broadheads - 200gn - 3 Pack",
    "priceAud": 44.95,
    "priceGbp": 23,
    "priceUsd": 29,
    "cat": "Broadhead & Specialty Points",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "terra firma venator broadheads - 200gn - 3 pack",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TF-VN-200.jpg?20240418111622"
  },
  {
    "title": "Zone Archery Kids Fiberglass Arrows - 26 Inch - 12",
    "priceAud": 49.95,
    "priceGbp": 26,
    "priceUsd": 32,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "zone archery kids fiberglass arrows - 26 inch - 12",
    "image": "https://www.apexhunting.com.au/assets/thumbL/TP-TPBJ-7026.png?20221201121345"
  },
  {
    "title": "AAE MAX Stealth Vanes",
    "priceAud": 22.95,
    "priceGbp": 12,
    "priceUsd": 15,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "aae max stealth vanes",
    "image": "https://www.apexhunting.com.au/assets/thumbL/AAE-MSxxxxx.jpg?20240202124606"
  },
  {
    "title": "Arrow Cutting Service 31\"",
    "priceAud": 15,
    "priceGbp": 8,
    "priceUsd": 10,
    "cat": "Fletched Arrows",
    "speed": null,
    "weight": null,
    "ata": null,
    "seoKw": "arrow cutting service 31\"",
    "image": "https://www.apexhunting.com.au/assets/thumbL/Cutting-xxx.jpg?20241008144729"
  }
];

const generateProducts = (): Product[] => {
  const products: Product[] = [];
  
  baseBows.forEach((b, i) => {
    products.push({
      id: `bow-${i}`,
      title: b.title,
      price_gbp: b.priceGbp,
      price_aud: b.priceAud,
      price_usd: b.priceUsd,
      category: b.cat,
      specs: { speed: b.speed, weight: b.weight, ata: b.ata },
      short_desc: 'High performance archery equipment for the serious shooter.',
      full_seo_desc: `The ${b.title} is precision engineered for maximum performance. Featuring top tier materials and our latest technology. Target keywords: ${b.seoKw}.`,
      meta_title: `${b.title} - Apex Archery Australia`,
      meta_desc: `Buy the ${b.title} online. Fast global shipping from Australia.`,
      in_stock: true,
      image_url: b.image
    });
  });

  baseArrows.forEach((a, i) => {
    products.push({
      id: `arrow-${i}`,
      title: a.title,
      price_gbp: a.priceGbp,
      price_aud: a.priceAud,
      price_usd: a.priceUsd,
      category: a.cat,
      specs: { },
      short_desc: 'Precision grade archery arrows and components.',
      full_seo_desc: `${a.title} - engineered for straightness, durability and performance. Target keywords: ${a.seoKw}.`,
      meta_title: `${a.title} - Apex Archery Australia`,
      meta_desc: `Buy the ${a.title} online. Fast global shipping from Australia.`,
      in_stock: true,
      image_url: a.image
    });
  });

  return products;
};

export const products = generateProducts();

export const blogPosts: BlogPost[] = [
  { id: 'bp-1', title: "Best Compound Bow for Hunting: Australian Game (2026 Guide)", snippet: "Looking for the best compound bow for hunting? Discover the most lethal setups for tackling tough Australian conditions.", readingTime: "8 min", targetKeywords: ["best compound bow for hunting", "hunting bows australia"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+1" },
  { id: 'bp-2', title: "Bowhunting Regulations in Australia: State-by-State Breakdown (NSW, VIC, QLD)", snippet: "Stay legal. Everything you need to know about licensing and permits.", readingTime: "12 min", targetKeywords: ["bowhunting laws australia", "hunting permit nsw"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+2" },
  { id: 'bp-3', title: "How to Choose a Hunting Bow: A Complete Guide for Australians", snippet: "Learn exactly how to choose a hunting bow for your specific needs and target game.", readingTime: "5 min", targetKeywords: ["how to choose a hunting bow", "archery draw weight"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+3" },
  { id: 'bp-4', title: "Carbon vs Aluminium Arrows: Which is Best for Australian Outback Conditions?", snippet: "Durability meets precision. We test the top arrow materials.", readingTime: "7 min", targetKeywords: ["carbon vs aluminium arrows", "outback archery"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+4" },
  { id: 'bp-5', title: "Mechanical vs Fixed Broadheads: Terminal Ballistics on Feral Pigs and Deer", snippet: "What actually works when hitting heavy bone? We look at the data.", readingTime: "10 min", targetKeywords: ["fixed vs mechanical broadheads", "hunting feral pigs"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+5" },
  { id: 'bp-6', title: "Tuning Your Compound Bow Cam System for Maximum Arrow Speed", snippet: "Squeeze every FPS out of your setup with these advanced tuning tips.", readingTime: "9 min", targetKeywords: ["cam tuning", "increase arrow speed"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+6" },
  { id: 'bp-7', title: "Archery for Beginners Australia: How to Get Started", snippet: "Archery for beginners australia: Find a local community, get your first bow, and start hitting the X-ring.", readingTime: "6 min", targetKeywords: ["archery for beginners australia", "archery clubs australia"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+7" },
  { id: 'bp-8', title: "Understanding IBO Speed: What Does 340+ FPS Actually Mean in the Field?", snippet: "Demystifying manufacturer speed ratings and real-world chronographs.", readingTime: "7 min", targetKeywords: ["IBO speed", "compound bow FPS"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+8" },
  { id: 'bp-9', title: "Best Archery Sights for Low-Light Hunting: Single Pin vs Multi-Pin", snippet: "Don't lose your pin when it counts. Reviewing the brightest optics.", readingTime: "8 min", targetKeywords: ["archery sights", "low light hunting"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+9" },
  { id: 'bp-10', title: "How to Care for Your Bowstrings in Extreme Australian Summer Heat", snippet: "Prevent string stretch and peep rotation in 40°C weather.", readingTime: "4 min", targetKeywords: ["bowstring wax", "archery maintenance"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+10" },
  { id: 'bp-11', title: "Arrow Spine Selection Chart: Matching Arrow Stiffness to Bow Poundage", snippet: "The ultimate guide to perfectly spined arrows for tight groups.", readingTime: "11 min", targetKeywords: ["arrow spine chart", "arrow stiffness"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+11" },
  { id: 'bp-12', title: "Bowfishing in Australia: Gear, Locations, and Legalities", snippet: "Take your archery skills to the water. A primer on bowfishing carp.", readingTime: "8 min", targetKeywords: ["bowfishing australia", "bowfishing gear"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+12" },
  { id: 'bp-13', title: "Compound Bow Maintenance Checklist Before Heading into the Bush", snippet: "Don't let gear failure ruin your hunt. Check these 10 things.", readingTime: "6 min", targetKeywords: ["bow maintenance", "hunting checklist"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+13" },
  { id: 'bp-14', title: "Target Archery vs 3D Field Archery: Rules, Distances, and Setups", snippet: "Comparing the two most popular competitive archery disciplines.", readingTime: "7 min", targetKeywords: ["3d archery", "target archery"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+14" },
  { id: 'bp-15', title: "Choosing the Right Release Aid: Index Finger Wrist Strap vs Thumb Trigger", snippet: "Pros and cons of the most popular release styles.", readingTime: "9 min", targetKeywords: ["archery release aid", "thumb trigger vs wrist strap"], imageUrl: "https://placehold.co/600x400/111111/EA580C/png?text=Blog+15" },
];

export const faqs: Faq[] = [
  { question: "Do I need a firearms license to purchase a compound bow in Australia?", answer: "No. In all Australian states and territories, compound bows are not classified as firearms and do not require a license to purchase, own, or use. However, you must have a lawful reason to possess one (like target shooting or hunting) and use it safely." },
  { question: "What is the minimum draw weight required to ethically hunt in Australia?", answer: "While state regulations vary slightly, a minimum of 45-50 lbs is generally recommended and legally required for medium game like deer and feral goats, and 50-60+ lbs for larger game like scrub bulls or large boars." },
  { question: "What is the £100 / $200 minimum order requirement on your store?", answer: "Due to high international and express domestic freight costs for bulky archery equipment, our checkout requires a minimum cart value of £100 GBP (or approx $200 AUD) to process an order." },
  { question: "Can you ship compound bows and broadheads internationally?", answer: "Yes. We offer Express Global Shipping via DHL. Please ensure you check your local customs regulations regarding the importation of archery equipment and broadheads." },
  { question: "How do I select the right arrow spine for my bow setup?", answer: "Arrow spine depends on your draw weight, draw length, and the weight of your broadhead/point. Check out our 'Arrow Spine Selection Chart' in the blog, or use our interactive Bow Selector Quiz for a recommendation." },
  { question: "Are your compound bows covered under manufacturer lifetime limb warranty?", answer: "All flagship compound bows we sell come with the original manufacturer's limited lifetime warranty on the riser and limbs to the original owner. Strings and cables are considered wear items." },
  { question: "How are hunting bows packaged to prevent damage during long-distance transit?", answer: "Bows are shipped in custom-engineered, heavy-duty double-corrugated cardboard boxes with high-density foam inserts to suspend the cams and riser, ensuring zero damage during express transit." },
  { question: "Can I adjust the draw weight and draw length myself, or do I need a bow press?", answer: "Draw weight can usually be adjusted at home using an Allen key on the limb bolts. Draw length adjustments depend on the bow model; some feature rotating modules adjustable with an Allen key, while others require a bow press to change modules or cams." },
];
